### PR TITLE
Config: Enable owners labels

### LINKED ISSUE #12: config: setup OWNER and OWNER_ALIASES files 3scale/3scale-ops repos
## Why?

To use the `approvers`, `lgtm` and `blunderbuss` plugins, each repo should have an OWNERS file to determine who can review or approve incoming PRs.

## How?

By creating OWNERS files in the repos tree to enable reviewers and approvers assignation.

## Requirements

 - [x] Create OWNERS_ALIASES on each repo managed by prow
 - [x] Create OWNERS on each repo managed by prow 
 
## Acceptance Criteria

 - [x] OWNERS_ALIASES file is created on each repo managed by prow
 - [x] OWNERS  file is created on each repo managed by prow 
 
## Notes

/kind feature
/priority important-soon
/label size/s

Closes #6

### PR DESCRIPTION
**Pull request by raelga**
Closes #12 

/kind feature
/priority important-soon
/label size/s 
/assign

### CODE REVIEW

**Comment by slopezz** [comment]
Should I review it @raelga ? it ahs WIP on the issue title

**Comment by raelga** [comment]
> Should I review it @raelga ? it has WIP on the issue title

With https://github.com/3scale-ops/test-infra/pull/14 merged, now is ready to be reviewed.

**Pull request merged**
