### PR TITLE
feat: add release tag for 3cale-ops/saas-operator

### PR DESCRIPTION
**Pull request by raelga**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds a release tag t the 3scale-ops saas-operator repository.

### CODE REVIEW

**Comment by slopezz** [comment]
@raelga can we maybe add the tag to all operators? prometheus-exporter, marin3r..?

**Comment by raelga** [comment]
@slopezz Added to the entire 3scale-ops org.

/approve

**Pull request merged**
